<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Student extends Model
{
    //默认是以类名为表名
    // 指定表
    protected $table = 'student';
    //指定主键,默认为id
    protected $primaryKey = 'id';
    //自动维护时间戳,即created_at 和updated_at 字段 默认开启,设置false 取消
    public $timestamps = true;
    //设置 自动维护时间的值 为时间戳
    protected function getDateFormat()
    {
        return time();
    }
    //默认 输出 created_at 和updated_at 字段值是带有格式的,改方法是使得值按照时间戳输出
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }

}
